### ISSUE TITLE
Bump to 0.2.212

### ISSUE THREAD

**Issue by miqm** [Azure/homebrew-bicep#1]
@anthony-c-martin - can we bump version to latest alpha release?

**Comment by anthony-c-martin** [comment]
I've submitted a PR. Note that this repo isn't the one pointed to by the install instructions, but I think going forward it's the one we should use. I'll add a task to the main Bicep board to track that.

**Comment by anthony-c-martin** [comment]
I've also submitted #3 so that we can automate this going forwards

**Comment by anthony-c-martin** [comment]
Addressed with #4
